### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by nar53** [feren-OS/feren-OS-Bug-Reporting#10] opened 2017-04-21 20:20 UTC
I've tried installing RC17 & 16.2 and get the same result with both, I can boot from the USB but installation fails when installing Grub. see image.

![feren-grub-fail](https://cloud.githubusercontent.com/assets/22550953/25294692/abb9790e-26e0-11e7-8053-0ec885c9689f.jpg)
Hope someone can help.

**Comment by scomnetgate** [comment] 2017-04-21 22:06
You can disable UEFI and Secure Boot and Enable Legacy Boot in bios and try again to install the system.

**Comment by nar53** [comment] 2017-04-22 08:07
Thanks for the info, worked perfectly. I'm so used to enabling UEFI these days it never occurred to me to disable it!

**Comment by scomnetgate** [comment] 2017-04-22 17:04
Many try make us believe that the windows 10 way it's the only way...

**Comment by feren** [comment] 2017-04-22 17:22
@nar53 Did you connect to WiFi?

**Comment by feren** [comment] 2017-04-22 17:23
Possible duplicate of #5 if the user hadn't connected to internet before installing

**Comment by nar53** [comment] 2017-04-22 17:50
I did connect to the net but not by WiFi. All went smoothly once I followed scomnetgate's suggestions.

**Comment by feren** [comment] 2017-04-22 19:24
Oh ok, hmm, odd, that it isn't installing the package ok...

**Comment by feren** [comment] 2017-05-30 08:48
This might be fixed in 2017.1, where the needed packages will now be stored in an ISO

**Comment by feren** [comment] 2017-08-15 15:09
Because of this issue is mentioned in the Ubuntu 16.04 Release Notes, this has been marked as Upstream.

**Closed** 2018-06-08 15:20 UTC
Labels: Bug, Confirmed, Help Needed, Importance: High, Upstream
